/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bs_dialog: typeof import('./src/components/bs_dialog/index.vue')['default']
    Bs_header: typeof import('./src/components/bs_header/index.vue')['default']
    Bs_main: typeof import('./src/components/bs_main/index.vue')['default']
    DarkMode: typeof import('./src/components/DarkMode.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
