// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['main']['DataModel']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['DataModel']['Delete'](arg1);
}

export function GetModelInfo(arg1) {
  return window['go']['main']['DataModel']['GetModelInfo'](arg1);
}

export function List(arg1, arg2, arg3) {
  return window['go']['main']['DataModel']['List'](arg1, arg2, arg3);
}

export function Modify(arg1) {
  return window['go']['main']['DataModel']['Modify'](arg1);
}

export function RunCode(arg1) {
  return window['go']['main']['DataModel']['RunCode'](arg1);
}

export function SaveModelInfo(arg1, arg2) {
  return window['go']['main']['DataModel']['SaveModelInfo'](arg1, arg2);
}

export function TestRunCode(arg1, arg2) {
  return window['go']['main']['DataModel']['TestRunCode'](arg1, arg2);
}
