// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDataModel(arg1) {
  return window['go']['main']['DataModel']['CreateDataModel'](arg1);
}

export function DeleteDataModel(arg1) {
  return window['go']['main']['DataModel']['DeleteDataModel'](arg1);
}

export function GetDataModelList(arg1, arg2, arg3) {
  return window['go']['main']['DataModel']['GetDataModelList'](arg1, arg2, arg3);
}

export function ModifyDataModel(arg1) {
  return window['go']['main']['DataModel']['ModifyDataModel'](arg1);
}
