// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';
import {model} from '../models';

export function Create(arg1:repository.CreateTemplate):Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function DeleteByCode(arg1:string):Promise<void>;

export function DeleteTreeNode(arg1:string):Promise<void>;

export function GetChildrenByCode(arg1:string):Promise<Array<model.CodeTemplate>>;

export function GetCode(arg1:string):Promise<string>;

export function GetTpByCode(arg1:string):Promise<model.CodeTemplate>;

export function GetTree():Promise<Array<repository.SchemeTree>>;

export function GetTreeByCode(arg1:string):Promise<Array<repository.SchemeTree>>;

export function List(arg1:repository.QryTemplate,arg2:number,arg3:number):Promise<Array<model.CodeTemplate>>;

export function Modify(arg1:repository.ModifyTemplate):Promise<void>;

export function ProgrammeList():Promise<Array<model.Scheme>>;

export function SaveCode(arg1:string,arg2:string):Promise<void>;
