// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';
import {model} from '../models';

export function Create(arg1:repository.RequestCreateTemplate):Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function GetCode(arg1:string):Promise<string>;

export function List(arg1:string,arg2:number,arg3:number):Promise<Array<model.CodeTemplate>>;

export function Modify(arg1:repository.RequestModifyTemplate):Promise<void>;

export function SaveCode(arg1:string,arg2:string):Promise<void>;
