// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['main']['Template']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['Template']['Delete'](arg1);
}

export function DeleteByCode(arg1) {
  return window['go']['main']['Template']['DeleteByCode'](arg1);
}

export function DeleteTreeNode(arg1) {
  return window['go']['main']['Template']['DeleteTreeNode'](arg1);
}

export function GetChildrenByCode(arg1) {
  return window['go']['main']['Template']['GetChildrenByCode'](arg1);
}

export function GetCode(arg1) {
  return window['go']['main']['Template']['GetCode'](arg1);
}

export function GetTpByCode(arg1) {
  return window['go']['main']['Template']['GetTpByCode'](arg1);
}

export function GetTree() {
  return window['go']['main']['Template']['GetTree']();
}

export function GetTreeByCode(arg1) {
  return window['go']['main']['Template']['GetTreeByCode'](arg1);
}

export function List(arg1, arg2, arg3) {
  return window['go']['main']['Template']['List'](arg1, arg2, arg3);
}

export function Modify(arg1) {
  return window['go']['main']['Template']['Modify'](arg1);
}

export function ProgrammeList() {
  return window['go']['main']['Template']['ProgrammeList']();
}

export function SaveCode(arg1, arg2) {
  return window['go']['main']['Template']['SaveCode'](arg1, arg2);
}
